### ISSUE TITLE
pääsivun näkymä yksittäisen itemin katsomisen (hakukentän käyttö) jälkeen...

### ISSUE THREAD

**Issue by Jpuksu** [mm-taigarevolution/tas_web_app#1]
1. kirjoita hakukenttään artikkelin nimi. esim donkey 
2. klikkaa itemia 
3. klikkaa selaimen back.buttonia
--> search-kenttä tyhjänä (tämä ok) mutta donkey kuva vain näkyvillä vaikka etusivun näkymät näkyvissä.

**Comment by mm-taigarevolution** [comment]
Kassos toimiiko. Muutin niin että sivun tila säilyy samana kuin siitä poistuttaessa.

**Comment by Jpuksu** [comment]
Jees, ny toimii noin. Eli kun hakukenttään kirjaittaa esim don ja klikkaa itemia ja tämän jälkeen selaimen back-nappia niin näkymä palautuu takain. Eli "don"-kirjaimet hakukentässä. Tää o hyvä ja case closed.
