### ISSUE TITLE
Yksittäisen item-näkymällä pyörii muidenkin tuotteiden kuvia

### ISSUE THREAD

**Issue by Jpuksu** [mm-taigarevolution/tas_web_app#4]
Eli kun klikkaat jotain tuotetta, niin esim arabia-kannun kohalla pyörii kuparipannun kuva .
Toisin sanoen toi kuvarullan funktio pois ite tarjousksen-/huutmasen näkymältä. 
Tai onko toi tarkoituksella että tuotteella voi olla useita kuvia mutta sulla kuvat loppu ja samoja kuvia joutunu käyttään ?

**Comment by mm-taigarevolution** [comment]
Juurikin näin, kuvat loppui :-D ja stubidatassa samoja kuvia kaikilla itemeillä. Kuvia voi olla asiakkaan mukaan jopa 100 kpl per itemi joita pitää pystyä kattelemaan kun avaa detailnäkymän.

**Comment by Jpuksu** [comment]
Jeps. Clousaan tämän.
